plugins {
    id 'java'
    id 'application'
}

group = 'de.samson_elektronik'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.53.2.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'de.samson_elektronik.gui.MainFrame'
}